### ISSUE TITLE
Task list for completing rough draft

### ISSUE THREAD

**Issue by sjoyal** [sjoyal/sjoyal.github.io#2]
- [x] **Introduction**
- [x] **Body**
  - [x] Growth vs Fixed Mindset
    - [x] Fixed Traits
    - [x] Growth Traits
  - [x] An Example - Learning to play the guitar
    - [x] Natural Ability (Running from difficulty)
    - [x] Love the Challenge (Playing for others, acknowledge my practice)
  - [x] How to Apply - TIY
    - [x] Acknowledge Fixed Traits within Myself
    - [x] Embrace Failures
    - [x] Commit to the Process
- [x] **Conclusion**
